org: erikthedeveloper
app: portfolio
service: contact-form-v2

custom:
  secrets: ${file(secrets.json)}

provider:
  lambdaHashingVersion: "20201221"
  name: aws
  runtime: nodejs14.x
  stage: ${self:custom.secrets.NODE_ENV}
  region: us-east-1
  environment: 
    NODE_ENV: ${self:custom.secrets.NODE_ENV}
    MAIN_EMAIL: ${self:custom.secrets.MAIN_EMAIL}
    SECONDARY_EMAIL: ${self:custom.secrets.SECONDARY_EMAIL}
    DOMAIN: ${self:custom.secrets.DOMAIN}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action: "ses:SendEmail"
          Resource: "*"
  apiGateway:
    shouldStartNameWithService: true

functions:
  send:
    handler: handler.send
    events:
      - http:
          path: email/send
          method: post
          cors: true
