---
label: Project
hide_body: true
fields:
- type: text
  name: title
  label: title
- type: text
  name: client
  label: client
- type: text
  name: description
  label: description
- type: datetime
  name: date
  label: date
- type: field_group_list
  name: media
  label: media
  fields:
  - type: text
    name: type
    label: type
  - type: list
    name: sources
    label: sources
- type: list
  name: skills
  label: skills
- type: field_group_list
  name: links
  label: links
  fields:
  - type: text
    name: target
    label: target
  - type: text
    name: href
    label: href
